# Generated by Django 4.2.10 on 2024-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="accessible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="person",
            name="origination_state",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="person",
            name="pet_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("Sedan", "Sedan"),
                    ("SUV", "SUV"),
                    ("Minivan", "Minivan"),
                    ("Van", "Van"),
                    ("Truck", "Truck"),
                    ("Other", "Other"),
                ],
                default="Sedan",
                max_length=20,
            ),
        ),
    ]
