# Generated by Django 4.2.10 on 2024-03-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_person_gas_mileage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="gas_mileage",
        ),
    ]
